name: Update Dashboard

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-processor:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install Libraries
        run: pip install -r requirements.txt
        
      - name: Run Python Script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python process_data.py
        
      - name: Save JSON to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/dashboard.json
          git commit -m "Auto-update dashboard [skip ci]" || exit 0
          git push
